---
title: "unique-code"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(here)
library(rio)
library(ggplot2)
library(Hmisc)
library(lubridate)
```

# import data
```{r}
df_ml1 <- import(here("data", "sci-cur-cr-lib1-data.csv")) %>% 
  mutate(batch = "lib1")
df_ml2 <- import(here("data", "scicur-comp-lib2.csv")) %>% 
  mutate(batch = "lib2")
df_mc <- import(here("data", "scicur-comp-con-071822-1548.csv")) %>% 
  mutate(batch = "con")
df_q <- import(here("data", "scicur-comp-lib.csv"))

df_m <- rbind(df_ml1, df_ml2, df_mc)
```

```{r}
clean_qualtrics1 <- function(df_q) {
  df_q[3:nrow(df_q),1:ncol(df_q)] %>% 
    janitor::clean_names() %>% 
    filter(distribution_channel != "preview" & duplicated(.) == F)
}

clean_mturk <- function(df_m) {
  df_m %>% 
    janitor::clean_names() %>% 
    rename(., id = amazon_identifier) %>% 
    rename(., entered_code = actual_completion_code) %>% 
    mutate(entered_code = as.numeric(entered_code), 
             code_yn = if_else(is.na(entered_code) == T, 0, 1),
           submitted = if_else(approval_status == "Not Submitted", 0, 1)) %>% 
    select(id, submitted, code_yn, entered_code, approval_status, submitted, batch)
}

check_duplicates <- function(df_m, df_q) {
  duplicates1 <- if_else(nrow(unique(df_m)) != nrow(df_m), 1, 0)
  duplicates2 <- if_else(nrow(unique(df_q)) != nrow(df_q), 1, 0)
  duplicates <- if_else(duplicates1 == 1, if_else(duplicates2 == 0, 1, 3), if_else(duplicates2 == 1, 2, 0))
  
  if(duplicates == 0) {
    duplicates
  }
  else(
    if(duplicates == 3) {
      stop("Check df1 and df2 for duplicates.")
    }
    else(
      if(duplicates == 1) {
        stop("Check df1 for duplicates.")
      }
      else(
        stop("Check df2 for duplicates.")
      )
    )
  )
  
}

clean_qualtrics2 <- function(df_q) {
  df_q %>% 
  select(id, unique_code, finished, consent1) %>% 
    mutate(unique_code = as.numeric(unique_code),
           con = if_else(consent1 == "I give my consent.", 1, 0),
           done = if_else(finished == T, if_else(con == 1, 1, 0), 0))
}


match_dfs <- function(df_m, df_q) {
  left_join(df_m, df_q, by = "id") %>% 
    select(id, submitted, unique_code, entered_code, code_yn, everything())
}

clean_matchdf <- function(df_j) {
  df_j %>% 
    mutate(match = if_else(code_yn == 1, if_else(
      as.numeric(entered_code) == as.numeric(unique_code), 1, 0
    ), 2),
    pending = if_else(approval_status == "Pending", 1, 0)) %>% 
    select(id, match, submitted, pending, contains("code"), approval_status, batch)
}
```

```{r}
mtchr <- function(df_m, df_q) {
  df_mc <- df_m %>% 
    clean_mturk()
  df_qc1 <- df_q %>% 
    clean_qualtrics1
  
  check_duplicates(df_mc, df_qc1)
  
  df_qc2 <- df_qc1 %>% 
    clean_qualtrics2
  
  match_dfs(df_mc, df_qc2) %>% 
    clean_matchdf()
# would like to include a message that tells you if you have NAs in matches, if all matched, etc
}
```

```{r}
mtchr(df_m, df_q)


```

```{r}
df_mct <- df_m %>% 
  clean_mturk()

df_mct %>% 
  filter(is.na(entered_code) == T)

df_qct <- df_q %>% 
  clean_qualtrics1() %>% 
  clean_qualtrics2()
```

```{r}
test1 <- match_dfs(df_mct, df_qct)

test1c <- test1 %>% 
  clean_matchdf()
```

