---
title: "match-function"
output: html_document
---
# load libraries
```{r}
library(tidyverse)
library(here)
library(rio)
library(ggplot2)
library(Hmisc)
library(lubridate)
```

# code w pilot test data
## import data
```{r}
test_df <- import(here("data", "sc-test-data.csv"))
mturk_df <- import(here("data", "sc-mturk-file.csv"))
```

# Clean Qualtrics Data
```{r}
clean_qualtrics <- function(df) {
  df[3:nrow(df),1:ncol(df)] %>% 
  janitor::clean_names() %>% 
  select(id, unique_code, finished, consent1) %>% 
  mutate(con = if_else(consent1 == "I give my consent.", 1, 0),
         done = if_else(finished == T, if_else(con == 1, 1, 0), 0))
}
```

## test
```{r}
clean_qualtrics(test_df) # works!
qualtrics_dfc <- test_df %>% 
  clean_qualtrics()
```

# Clean MTurk Data
```{r}
clean_mturk <- function(df) {
df %>% 
  janitor::clean_names() %>% 
  rename(., id = amazon_identifier) %>% 
  rename(., entered_code = actual_completion_code) %>% 
  mutate(code_yn = if_else(is.na(entered_code) == T, 0, 1),
         submitted = if_else(approval_status == "Not Submitted", 0, 1)) %>% 
  select(id, submitted, code_yn, entered_code, approval_status, submitted)
}
```

## test
```{r}
clean_mturk(mturk_df) # works!

mturk_dfc <- mturk_df %>% 
  clean_mturk()
```

# Check for duplicates
```{r}
check_duplicates <- function(df1, df2) {
  duplicates1 <- if_else(nrow(unique(df1)) != nrow(df1), 1, 0)
  duplicates2 <- if_else(nrow(unique(df2)) != nrow(df2), 1, 0)
  duplicates <- if_else(duplicates1 == 1, if_else(duplicates2 == 0, 1, 3), if_else(duplicates2 == 1, 2, 0))
  
  if(duplicates == 0) {
    duplicates
  }
  else(
    if(duplicates == 3) {
      stop("Check df1 and df2 for duplicates.")
    }
    else(
      if(duplicates == 1) {
        stop("Check df1 for duplicates.")
      }
      else(
        stop("Check df2 for duplicates.")
      )
    )
  )
  
}
```

## test
```{r}
check_duplicates(mturk_df, test_df)

mturk_dup <- rbind(mturk_df, mturk_df[2,])
test_dup <- rbind(test_df, test_df[2,])

check_duplicates(mturk_df, test_dup)
check_duplicates(mturk_dup, test_df)
check_duplicates(mturk_dup, test_dup)
# works!
```

# Create match dataset
```{r}
match_dfs <- function(df1, df2) {
  left_join(df1, df2, by = "id") %>% 
  select(id, submitted, unique_code, entered_code, code_yn, everything())
}
```

## test
```{r}
match_dfs(mturk_dfc, qualtrics_dfc) # works!

match_dfc <- match_dfs(mturk_dfc, qualtrics_dfc)
```

# Clean match dataset
```{r}
clean_matchdf <- function(df) {
  df %>% 
  mutate(match = if_else(code_yn == 1, if_else(
    as.numeric(entered_code) == as.numeric(unique_code), 1, 0
    ), 2),
    pending = if_else(approval_status == "Pending", 1, 0)) %>% 
  select(id, match, submitted, pending, contains("code"), approval_status)
}
```

## test
```{r}
match_dfc %>% 
  clean_matchdf() # works!
```

## Match dataset output
```{r}
output_match <- function(df) {
  
  pending_df <- df %>% 
    filter(match == 1 & pending == 1) %>% 
    select(id, unique_code)

  nomatch_df <- df %>% 
    filter(match == 0) %>% 
    select(id, contains("code"))

  nosubmit_df <- df %>% 
    filter(submitted == 0) %>% 
    select(id, match)
  
  if(nrow(nomatch_df) != 0) {
    nomatch_df
  }
  else("All codes match.")

  if(nrow(pending_df) != 0) {
    pending_df
  }
  else("No HITs pending.")
  
  if(nrow(nosubmit_df) != 0) {
    nosubmit_df
  }
  else("All HITs were submitted.")
}
```

## test
```{r}
match_dfc %>% 
  output_match()
```

