---
title: "test-data"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(here)
library(rio)
library(ggplot2)
library(Hmisc)
library(lubridate)
```

# code w pilot test data
## import data
```{r}
test_df <- import(here("data", "sc-test-data.csv"))
mturk_df <- import(here("data", "sc-mturk-file.csv"))
```

## clean data
```{r}
test_df1 <- test_df[3:nrow(test_df),1:ncol(test_df)] %>% 
  janitor::clean_names() %>% 
  select(id, unique_code, finished, consent1) %>% 
  mutate(con = if_else(consent1 == "I give my consent.", 1, 0),
         done = if_else(finished == T, if_else(con == 1, 1, 0), 0))

nrow(unique(test_df1)) == nrow(test_df1)

mturk_df1 <- mturk_df %>% 
  janitor::clean_names() %>% 
  rename(., id = amazon_identifier) %>% 
  rename(., entered_code = actual_completion_code) %>% 
  mutate(code_yn = if_else(is.na(entered_code) == T, 0, 1),
         submitted = if_else(approval_status == "Not Submitted", 0, 1)) %>% 
  select(id, submitted, code_yn, entered_code, approval_status, submitted)

nrow(unique(mturk_df1)) == nrow(mturk_df1)

match_df <- left_join(mturk_df1, test_df1, by = "id") %>% 
  select(id, submitted, unique_code, entered_code, code_yn, everything())
```

# match data
```{r}
# match_df1 <- match_df %>% 
#   mutate(match = if_else(code_yn == 1, if_else(
#     as.numeric(entered_code) == as.numeric(unique_code), 1, 0
#     ), 2),
#     pending = if_else(approval_status == "Pending", 1, 0)) %>% 
#   select(id, match, submitted, pending, contains("code"), approval_status)
# 
# pending_df <- match_df1 %>% 
#   filter(match == 1 & pending == 1) %>% 
#   select(id, unique_code)
# 
# nomatch_df <- match_df1 %>% 
#   filter(match == 0) %>% 
#   select(id, contains("code"))
# 
# nosubmit_df <- match_df1 %>% 
#   filter(submitted == 0) %>% 
#   select(id, match)

```

